/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAX_LISTA_SIZE 5
#define MAX_MATRICOLA_SIZE 20
#define MAX_NAME_SIZE 128

struct Matricola {
	char matricola[MAX_MATRICOLA_SIZE];
};
typedef struct Matricola Matricola;
#ifdef __cplusplus
extern "C" bool_t xdr_Matricola(XDR *, Matricola*);
#elif __STDC__
extern  bool_t xdr_Matricola(XDR *, Matricola*);
#else /* Old Style C */
bool_t xdr_Matricola();
#endif /* Old Style C */


struct Studente {
	char matricola[MAX_MATRICOLA_SIZE];
	char nome[MAX_NAME_SIZE];
	char cognome[MAX_NAME_SIZE];
	int voto;
};
typedef struct Studente Studente;
#ifdef __cplusplus
extern "C" bool_t xdr_Studente(XDR *, Studente*);
#elif __STDC__
extern  bool_t xdr_Studente(XDR *, Studente*);
#else /* Old Style C */
bool_t xdr_Studente();
#endif /* Old Style C */


struct Output {
	Studente lista_studenti[MAX_LISTA_SIZE];
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


#define RPC ((rpc_uint)0x20000013)
#define RPCVERS ((rpc_uint)1)

#ifdef __cplusplus
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern "C" int * elimina_prenotazione_1(Matricola *, CLIENT *);
extern "C" int * elimina_prenotazione_1_svc(Matricola *, struct svc_req *);
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern "C" Output * visualizza_voto_maggiore_soglia_1(int *, CLIENT *);
extern "C" Output * visualizza_voto_maggiore_soglia_1_svc(int *, struct svc_req *);

#elif __STDC__
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1(Matricola *, CLIENT *);
extern  int * elimina_prenotazione_1_svc(Matricola *, struct svc_req *);
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern  Output * visualizza_voto_maggiore_soglia_1(int *, CLIENT *);
extern  Output * visualizza_voto_maggiore_soglia_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define ELIMINA_PRENOTAZIONE ((rpc_uint)1)
extern  int * elimina_prenotazione_1();
extern  int * elimina_prenotazione_1_svc();
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA ((rpc_uint)2)
extern  Output * visualizza_voto_maggiore_soglia_1();
extern  Output * visualizza_voto_maggiore_soglia_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_H_RPCGEN */
