/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
elimina_prenotazione_1(argp, clnt)
	Matricola *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ELIMINA_PRENOTAZIONE, xdr_Matricola, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

Output *
visualizza_voto_maggiore_soglia_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static Output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VISUALIZZA_VOTO_MAGGIORE_SOGLIA, xdr_int, argp, xdr_Output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
