/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Prenotazioni *
visualizza_prenotazioni_1(argp, clnt)
	Brand *argp;
	CLIENT *clnt;
{
	static Prenotazioni clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VISUALIZZA_PRENOTAZIONI, xdr_Brand, argp, xdr_Prenotazioni, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
elimina_monopattino_1(argp, clnt)
	Id_seriale *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ELIMINA_MONOPATTINO, xdr_Id_seriale, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
