/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Prenotazione(xdrs, objp)
	XDR *xdrs;
	Prenotazione *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->id_seriale, ID_SERIALE_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->carta_id, CARTA_ID_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->brand, BRAND_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->img_folder, MAX_FOLDER_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Prenotazioni(xdrs, objp)
	XDR *xdrs;
	Prenotazioni *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->prenotazioni, MAX_NUM_PREN, sizeof(Prenotazione), (xdrproc_t)xdr_Prenotazione))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Brand(xdrs, objp)
	XDR *xdrs;
	Brand *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->brand, BRAND_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Id_seriale(xdrs, objp)
	XDR *xdrs;
	Id_seriale *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->id_seriale, ID_SERIALE_LENGTH, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}
